name: Fullstack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest

    env:
      CI: true
      MONGO_URL: monogodb://localhost/portfolio

    strategy:
      matrix:
        node-version: [21.x, 20.x]
        mongodb-version: [ '8.0']
        

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.12.0
        with: 
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run backend tests
        run: npm test
        working-directory: ./backend

      - name: Build backend
        run: npm run build
        working-directory: ./backend

  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
